[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd webapp && npm ci"]

[phases.build]
cmds = ["cd webapp && npm run build"]

[start]
cmd = "npx -y serve webapp/dist -s -l tcp://0.0.0.0:3000"
